title: Watch A Turtle Blog
theme: minima
show_downloads: false

minima:
  youtube: watchaturtle
  youtube_channel: UCsz741u63L-kPTxQIegUJiA
  youtube_channel_name: watchaturtle

header_pages:
  - pi.md
  - about.md
